### ISSUE TITLE
Lies!

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-curriculum/react-component-mounting-and-unmounting#6]
@ddbrennan thank you for opening an issue.
please keep in mind individuals take time to read through, and address, issues. 
if you open further issues, please provide additional context.

**Comment by DanielSeehausen** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
